### PR TITLE
Adding model output for FDLMN model and stan code for TDLMN model.

### PR DESCRIPTION
**Pull request by IsaacMacarthur**
Adding the submission files for the FDLMN model and the stan code for TDLMN model, along which misc changes to HMLR_submission_creator.R to make it work with Unity.

### CODE REVIEW

**Comment by trobacker** [comment]
Perhaps I'm being pedantic, but is there a place to see and keep track of what the different knobs represent? 

I see `sets the knob sd_structure to T, time_treatment to D, time_model to L, distribution to M, and spatial_correlation to N` and while I can intuitively guess what some of these mean, I think over time and for others it might be confusing. I support keeping the knobs but I think it's also important to keep track of what they represent. Going to merge anyway for now.

**Review by trobacker — APPROVED** [review]
LGTM but I want to add a comment: 
Perhaps I'm being pedantic, but is there a place to see and keep track of what the different knobs represent?

I see sets the knob sd_structure to T, time_treatment to D, time_model to L, distribution to M, and spatial_correlation to N and while I can intuitively guess what some of these mean, I think over time and for others it might be confusing. I support keeping the knobs but I think it's also important to keep track of what they represent. Going to merge anyway for now.

**Comment by nickreich** [comment]
@trobacker I think the knob info is contained here: https://github.com/reichlab/variant-nowcast-model-dev-retro/blob/main/auxiliary-data/Model_knobs.json

**Review by nickreich — APPROVED** [review]
LGTM!

**Pull request merged**
